
TYPO3:
  Media:
    behaviourFlag: '1.2'
    asyncThumbnails: true
    thumbnailPresets: {  }
    autoCreateThumbnailPresets: true
    asset:
      modelMappingStrategy:
        default: TYPO3\Media\Domain\Model\Document
        patterns:
          '[image/.*]':
            className: TYPO3\Media\Domain\Model\Image
          '[audio/.*]':
            className: TYPO3\Media\Domain\Model\Audio
          '[video/.*]':
            className: TYPO3\Media\Domain\Model\Video
    image:
      defaultOptions:
        quality: 90
        convertCMYKToRGB: true
    thumbnailGenerators:
      TYPO3\Media\Domain\Model\ThumbnailGenerator\DocumentThumbnailGenerator:
        resolution: 120
        supportedExtensions:
          - pdf
          - eps
          - ai
        paginableDocuments:
          - pdf
      TYPO3\Media\Domain\Model\ThumbnailGenerator\FontDocumentThumbnailGenerator:
        supportedExtensions:
          - ttf
          - otf
  DocTools:
    collections:
      Media:
        commandReferences:
          - 'Media:Commands'
        references:
          - 'Media:ViewHelpers'
          - 'Media:Validators'
    commandReferences:
      'Media:Commands':
        title: 'Media Command Reference'
        packageKeys:
          - TYPO3.Media
        savePathAndFilename: '%FLOW_PATH_PACKAGES%Neos/TYPO3.Media/Documentation/References/Commands.rst'
    references:
      'Media:Validators':
        title: 'Media Validator Reference'
        savePathAndFilename: '%FLOW_PATH_PACKAGES%Neos/TYPO3.Media/Documentation/References/Validators.rst'
        affectedClasses:
          parentClassName: Neos\Flow\Validation\Validator\AbstractValidator
          classNamePattern: '/^TYPO3\\Media\\Validator\\.*$/i'
        parser:
          implementationClassName: TYPO3\DocTools\Domain\Service\FlowValidatorClassParser
      'Media:ViewHelpers':
        title: 'Media ViewHelper Reference'
        savePathAndFilename: '%FLOW_PATH_PACKAGES%Neos/TYPO3.Media/Documentation/References/ViewHelpers.rst'
        affectedClasses:
          parentClassName: Neos\FluidAdaptor\Core\ViewHelper\AbstractViewHelper
          classNamePattern: '/^TYPO3\\Media\\ViewHelpers\\.*$/i'
        parser:
          implementationClassName: TYPO3\DocTools\Domain\Service\FluidViewHelperClassParser
          options:
            namespaces:
              typo3.media: TYPO3\Media\ViewHelpers
Neos:
  Flow:
    persistence:
      doctrine:
        eventListeners:
          TYPO3\Media\Domain\EventListener\ImageEventListener:
            events:
              - postRemove
            listener: TYPO3\Media\Domain\EventListener\ImageEventListener
    mvc:
      routes:
        TYPO3.Media:
          position: 'before TYPO3.Neos'
